/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;


/**
 *
 * @author admin
 */
public class frmTrangChu extends javax.swing.JFrame {
   //tk: huylong2004 mk: 123456
    private int x;          // vị trí X hiện tại của JLabel marquee
    private int step = 2;   // tốc độ chạy (pixels mỗi lần)
    /**
     * Creates new form frmTrangChu
     */
    public frmTrangChu() {
        initComponents();
              x = marquee.getX();  // lấy vị trí ban đầu của JLabel

        Timer timer = new Timer(30, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                x += step;
                
                 // Nếu chạm lề phải thì đổi hướng sang trái
                if (x + marquee.getWidth() >= getWidth()) {
                    step = -2;
                 // Nếu chạm lề trái thì đổi hướng sang phải
                } else if (x <= 0) {
                    step = 2;
                }

                marquee.setLocation(x, marquee.getY());
            }
        });

        timer.start();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnQLNhanVien = new javax.swing.JButton();
        btnQLPhong = new javax.swing.JButton();
        btnQLDV = new javax.swing.JButton();
        nutDangXuat = new javax.swing.JButton();
        btnQLBC = new javax.swing.JButton();
        btnQLHoaDon = new javax.swing.JButton();
        btnQLKH = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        marquee = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setText("TRANG CHỦ");
        jLabel1.setMaximumSize(new java.awt.Dimension(300, 70));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 220, -1));

        btnQLNhanVien.setBackground(new java.awt.Color(102, 102, 0));
        btnQLNhanVien.setForeground(new java.awt.Color(51, 255, 204));
        btnQLNhanVien.setText("👨‍💼 Quản Lý Nhân Viên");
        btnQLNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNhanVienActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 162, 57));

        btnQLPhong.setBackground(new java.awt.Color(102, 102, 0));
        btnQLPhong.setForeground(new java.awt.Color(51, 255, 204));
        btnQLPhong.setText("🛏️ Quản Lý Phòng");
        btnQLPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLPhongActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 160, 57));

        btnQLDV.setBackground(new java.awt.Color(102, 102, 0));
        btnQLDV.setForeground(new java.awt.Color(51, 255, 204));
        btnQLDV.setText("🛎 Quản Lý Dịch Vụ Sử Dụng ");
        btnQLDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLDVActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 190, 57));

        nutDangXuat.setBackground(new java.awt.Color(102, 102, 0));
        nutDangXuat.setForeground(new java.awt.Color(51, 255, 204));
        nutDangXuat.setText("Đăng Xuất");
        nutDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutDangXuatActionPerformed(evt);
            }
        });
        getContentPane().add(nutDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 20));

        btnQLBC.setBackground(new java.awt.Color(102, 102, 0));
        btnQLBC.setForeground(new java.awt.Color(51, 255, 204));
        btnQLBC.setText("📊 Quản Lý Báo Cáo, Thống Kê");
        btnQLBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLBCActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 200, 57));

        btnQLHoaDon.setBackground(new java.awt.Color(102, 102, 0));
        btnQLHoaDon.setForeground(new java.awt.Color(51, 255, 204));
        btnQLHoaDon.setText("📜 Quản Lý Hóa Đơn");
        btnQLHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLHoaDonActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 160, 57));

        btnQLKH.setBackground(new java.awt.Color(102, 102, 0));
        btnQLKH.setForeground(new java.awt.Color(51, 255, 204));
        btnQLKH.setText("👤 Quản Lý Khách Hàng");
        btnQLKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLKHActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 160, 57));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 204));
        jLabel5.setText("Penguin ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 160, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 204));
        jLabel8.setText("Hotel");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 100, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 110));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logocanhcut.png"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, -10, -1, 270));

        marquee.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        marquee.setForeground(new java.awt.Color(255, 0, 255));
        marquee.setText("Chào mừng bạn đã đến với khách sạn của chúng tôi !");
        getContentPane().add(marquee, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 51));
        jLabel7.setText("KHÁCH SẠN");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 220, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 51));
        jLabel6.setText("QUẢN LÝ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 160, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 102));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg1.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 410));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNhanVienActionPerformed
        // Tạo instance của form frmQLNhanVien và hiển thị nó
        frmQLNhanVien qlNhanVien = new frmQLNhanVien();
        qlNhanVien.setVisible(true);

        // Ẩn form hiện tại
        this.dispose();
    }//GEN-LAST:event_btnQLNhanVienActionPerformed

    private void btnQLPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLPhongActionPerformed
        // Tạo instance của form frmQLPhong và hiển thị nó
        frmQLPhong qlp = new frmQLPhong();
        qlp.setVisible(true);

        // Ẩn form hiện tại
        this.dispose();
    }//GEN-LAST:event_btnQLPhongActionPerformed

    private void btnQLDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLDVActionPerformed
        // Tạo instance của form frmQLPhong và hiển thị nó
        frmQLDichVuSuDung qldv = new frmQLDichVuSuDung();
        qldv.setVisible(true);

        // Ẩn form hiện tại
        this.dispose();
    }//GEN-LAST:event_btnQLDVActionPerformed

    private void nutDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutDangXuatActionPerformed
        // Tạo instance của form frmQLHoaDon và hiển thị nó
        frmDangNhap dangxuat = new frmDangNhap();
        dangxuat.setVisible(true);

        // Ẩn form hiện tại
        this.dispose();
    }//GEN-LAST:event_nutDangXuatActionPerformed

    private void btnQLBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLBCActionPerformed
        // Tạo instance của form frmQLBaoCaoThongKe và hiển thị nó
        frmBieuDoThongKe qlbc = new frmBieuDoThongKe();
        qlbc.setVisible(true);

        // Ẩn form hiện tại
        this.dispose();
    }//GEN-LAST:event_btnQLBCActionPerformed

    private void btnQLHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLHoaDonActionPerformed
         // Tạo instance của form frmQLBaoCaoThongKe và hiển thị nó
        frmQLHoaDon qlhd = new frmQLHoaDon();
        qlhd.setVisible(true);

        // Ẩn form hiện tại
        this.dispose();
    }//GEN-LAST:event_btnQLHoaDonActionPerformed

    private void btnQLKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLKHActionPerformed
        // Tạo instance của form frmQLKhachHang và hiển thị nó
        frmQLKhachHang qlkh = new frmQLKhachHang();
        qlkh.setVisible(true);

        // Ẩn form hiện tại
        this.dispose();
    }//GEN-LAST:event_btnQLKHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel background;
    private javax.swing.JButton btnQLBC;
    private javax.swing.JButton btnQLDV;
    private javax.swing.JButton btnQLHoaDon;
    private javax.swing.JButton btnQLKH;
    private javax.swing.JButton btnQLNhanVien;
    private javax.swing.JButton btnQLPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel marquee;
    private javax.swing.JButton nutDangXuat;
    // End of variables declaration//GEN-END:variables
}
